# Generated by Django 5.2.5 on 2025-08-21 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free (7 dias)'), ('premium', 'Premium (30 dias)'), ('platinum', 'Platinum (1 ano)')], max_length=20, unique=True)),
                ('max_funcionarios', models.PositiveIntegerField(default=1, help_text='Quantidade máxima de funcionários permitidos.')),
                ('max_lojas', models.PositiveIntegerField(default=1, help_text='Quantidade máxima de lojas permitidas.')),
            ],
        ),
    ]
