# Generated by Django 5.2.5 on 2025-09-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_grupo_user_nome_user_sobrenome_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grupo',
            field=models.SlugField(blank=True, max_length=150),
        ),
    ]
