# Generated by Django 5.2.5 on 2025-08-18 23:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('cargo', models.CharField(choices=[('barbeiro', 'Barbeiro'), ('cabeleireiro', 'Cabeleireiro(a)'), ('manicure', 'Manicure/Pedicure'), ('esteticista', 'Esteticista'), ('sobrancelha', 'Designer de Sobrancelha'), ('recepcao', 'Recepção'), ('outro', 'Outro')], default='barbeiro', max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator('^\\+?\\d{10,15}$', 'Informe telefone no formato internacional, ex.: +5585...')])),
                ('slug', models.SlugField(blank=True, max_length=160)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionarios', to='cadastro.loja')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ('nome',),
                'unique_together': {('loja', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, max_length=180)),
                ('descricao', models.TextField(blank=True)),
                ('duracao_minutos', models.PositiveSmallIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='cadastro.loja')),
                ('profissionais', models.ManyToManyField(blank=True, related_name='servicos', to='cadastro.funcionario')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
                'ordering': ('nome',),
                'unique_together': {('loja', 'slug')},
            },
        ),
    ]
