# Generated by Django 5.2.5 on 2025-08-31 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_funcionario_servico'),
    ]

    operations = [
        migrations.CreateModel(
            name='LojaAgendamentoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_interval_minutes', models.PositiveSmallIntegerField(default=15, help_text='Intervalo padrão entre slots (min). Ex.: 15, 20, 30.')),
                ('timezone_name', models.CharField(default='America/Fortaleza', help_text='Fuso horário da loja (ex.: America/Fortaleza)', max_length=64)),
                ('loja', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agendamento_config', to='cadastro.loja')),
            ],
        ),
        migrations.CreateModel(
            name='FuncionarioAgendaExcecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('is_day_off', models.BooleanField(default=False)),
                ('inicio', models.TimeField(blank=True, null=True)),
                ('fim', models.TimeField(blank=True, null=True)),
                ('almoco_inicio', models.TimeField(blank=True, null=True)),
                ('almoco_fim', models.TimeField(blank=True, null=True)),
                ('slot_interval_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas_excecoes', to='cadastro.funcionario')),
            ],
            options={
                'ordering': ('funcionario', 'data'),
                'unique_together': {('funcionario', 'data')},
            },
        ),
        migrations.CreateModel(
            name='FuncionarioAgendaSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('inicio', models.TimeField()),
                ('fim', models.TimeField()),
                ('almoco_inicio', models.TimeField(blank=True, null=True)),
                ('almoco_fim', models.TimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('slot_interval_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas_semanais', to='cadastro.funcionario')),
            ],
            options={
                'ordering': ('funcionario', 'weekday'),
                'unique_together': {('funcionario', 'weekday')},
            },
        ),
    ]
