# Generated by Django 5.2.5 on 2025-09-09 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_cliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cor_hex',
            field=models.CharField(default='#000000', help_text='Cor para exibir no calendário (ex.: #FF0000)', max_length=7),
        ),
    ]
