# Generated by Django 5.2.5 on 2025-08-31 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_funcionario_dias_semana_slot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='dias_semana',
        ),
    ]
