# Generated by Django 5.2.5 on 2025-08-31 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_remove_funcionario_dias_semana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='slot_interval_minutes',
        ),
    ]
