# Generated by Django 5.2.5 on 2025-09-09 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_funcionario_cor_hex'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormaPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=40, unique=True)),
                ('nome', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='loja',
            name='pagamentos_aceitos',
            field=models.ManyToManyField(blank=True, related_name='lojas', to='cadastro.formapagamento'),
        ),
        migrations.CreateModel(
            name='LojaHorario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')])),
                ('aberto', models.BooleanField(default=True)),
                ('inicio', models.TimeField(blank=True, null=True)),
                ('fim', models.TimeField(blank=True, null=True)),
                ('almoco_inicio', models.TimeField(blank=True, null=True)),
                ('almoco_fim', models.TimeField(blank=True, null=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='cadastro.loja')),
            ],
            options={
                'ordering': ['weekday'],
                'unique_together': {('loja', 'weekday')},
            },
        ),
    ]
